name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      libraryName: cfimager
      tagName: 1.7.3.4
    steps:
      - uses: actions/checkout@v4
        with:
          repository: nxp-imx/cfimager
          ref: ${{ env.tagName }}
          path: ${{ env.libraryName }}
          submodules: true
          
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          sdk: 8.1
          
      # - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
        
      - working-directory: ${{ env.libraryName }}
        shell: cmd
        run: msbuild /m .\src\cfimager.sln

      #  /p:Configuration=RelWithDebInfo 
      # - name: Archive Release
      #   uses: thedoctor0/zip-release@master
      #   with:
      #     type: 'zip'
      #     path: CactusViewer.exe
      #     directory: "${{ env.libraryName }}/bin"
      #     filename: "${{ env.libraryName }}-${{ github.ref_name }}.zip"
        
      # - name: Release prebuilt
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "${{ env.libraryName }}/bin/${{ env.libraryName }}-${{ github.ref_name }}.zip"
      #     allowUpdates: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
